# Generated by Django 5.2 on 2025-05-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='position',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
