# Generated by Django 5.2 on 2025-05-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_playerprofile_position_playerprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='positions',
            field=models.CharField(blank=True, help_text='Comma-separated position codes (e.g. GK,CB,LB)', max_length=200),
        ),
    ]
