# Generated by Django 5.2 on 2025-05-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_playerprofile_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma-separated language codes (e.g. en,hr,de)', max_length=200),
        ),
    ]
