# Generated by Django 5.2 on 2025-05-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_playerprofile_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='club',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
