# Generated by Django 5.2 on 2025-05-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_playerprofile_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='achievements',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
