# Generated by Django 5.2 on 2025-05-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_playerprofile_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='medical_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
