# Generated by Django 5.2 on 2025-05-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_playerprofile_medical_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='parental_consent_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('granted', 'Granted'), ('rejected', 'Rejected')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='privacy_settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
    ]
