# Generated by Django 5.2 on 2025-05-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_parentalconsentrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationtoken',
            old_name='is_used',
            new_name='used',
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='official_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='stadium_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubprofile',
            name='stadium_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fanprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fanprofile',
            name='favorite_team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
